### ISSUE TITLE
Internal error upon calling depositMethods

### ISSUE THREAD

**Issue by TwinkieWInkie** [CliffS/kraken-exchange#3]
This endpoint always responds with 
`{ error: [ 'EGeneral:Internal error' ] }`

I've called this method with a single string as argument, usually 'ETH' or 'XETH'.

**Comment by CliffS** [comment]
That's odd.  Sounds like a Kraken error.  Are you still getting it?

If I call the method with `ETH` as the parameter, I get back:

```javascript
[ { unixtime: 1529076408,
    rfc1123: 'Fri, 15 Jun 18 15:26:48 +0000' },
  [ { method: 'Ether (Hex)',
      limit: false,
      fee: '0.0000000000',
      'gen-address': true } ] ]
```

**Comment by CliffS** [comment]
Not heard back from @TwinkieWInkie so closing this issue.
